8 tests

diff --git a/pigs-show b/pigs-show
--- a/pigs-show
+++ b/pigs-show
@@ -4,6 +4,13 @@ REPONAME=".pig"
 
 filename="$(echo "$1" | cut -d':' -f2)"
 
+if echo "$1" | grep -qE '.+:.+'; then
+	:
+else
+	echo "$0: error: should have arguments in style [commit number]:[filename]" >& 2
+	exit 1
+fi
+
 if [ "$(echo "$1" | cut -d':' -f1)" = "" ]; then
 	#NO COMMIT GIVEN
 	if [ -f "$REPONAME/index/$filename" ]; then
