2 tests done

diff --git a/pigs-add b/pigs-add
--- a/pigs-add
+++ b/pigs-add
@@ -12,14 +12,17 @@ fi
 for filename in "$@"
 do
 	if [ -f "$filename" ]; then
-		if echo "$filename" | grep -qE "^[a-zA-Z0-9\.\-_]+$"; then
+		if echo $filename | grep -qE '^[a-zA-Z0-9][a-zA-Z0-9\._\-]*$'; then
 			cp "$filename" "$REPONAME/index"
 		else
-			echo "./$0: $filename is not an ordinary file and cannot be added - it has been excluded."
+			echo "./$0: error: '$filename' bad filename."
 		fi
 	else
 		if [ -f "$REPONAME/index/$filename" ]; then
 			rm "$REPONAME/index/$filename"
+		elif [ -d "$filename" ]; then
+			echo "$0: '$filename' is a repository and not a file" >& 2
+			exit 1
 		else
 			echo "$0: error: can not open '$filename'" >& 2
 			exit 1
