6 tests written

diff --git a/pigs-show b/pigs-show
--- a/pigs-show
+++ b/pigs-show
@@ -5,7 +5,7 @@ REPONAME=".pig"
 filename="$(echo "$1" | cut -d':' -f2)"
 
 if [ "$(echo "$1" | cut -d':' -f1)" = "" ]; then
-	#NO NUM
+	#NO COMMIT GIVEN
 	if [ -f "$REPONAME/index/$filename" ]; then
 		cat "$REPONAME/index/$filename"
 	else
@@ -15,19 +15,24 @@ if [ "$(echo "$1" | cut -d':' -f1)" = "" ]; then
 	
 	
 else	
-	#YESNUM
+	#COMMIT GIVEN
 	COMMIT="$(echo "$1" | cut -d':' -f1)"
-	if [ -d "$REPONAME/commits/commit$COMMIT" ]; then
-		if [ -f "$REPONAME/commits/commit$COMMIT/$filename" ]; then
-			cat "$REPONAME/commits/commit$COMMIT/$filename"
+	if echo "$COMMIT" | grep -qE '^[0-9]+$'; then
+		if [ -d "$REPONAME/commits/commit$COMMIT" ]; then
+			if [ -f "$REPONAME/commits/commit$COMMIT/$filename" ]; then
+				cat "$REPONAME/commits/commit$COMMIT/$filename"
+			else
+				echo "$0: error: '$filename' not found in commit $COMMIT" >& 2
+				exit 1
+			fi
 		else
-			echo "$0: error: '$filename' not found in commit $COMMIT" >& 2
+			echo "$0: error: unknown commit '$COMMIT'" >& 2
 			exit 1
 		fi
 	else
-		echo "$0: error: unknown commit '$COMMIT'" >& 2
-		exit 1
+		echo "$0: error: commit has to be a non-negative integer"
 	fi
+
 	
 	
 fi
