tests

diff --git a/pigs-log b/pigs-log
--- a/pigs-log
+++ b/pigs-log
@@ -1,3 +1,11 @@
 #!/bin/dash
 REPONAME=".pig"
+
+if [ -d "$REPONAME" ]; then
+	:
+else
+	echo "$0: error: pigs repository directory .pig not found" >& 2
+	exit 1
+fi
+
 cat "$REPONAME/log"
diff --git a/pigs-rm b/pigs-rm
--- a/pigs-rm
+++ b/pigs-rm
@@ -1,5 +1,13 @@
 #!/bin/dash
 REPONAME=".pig"
+
+if [ -d "$REPONAME" ]; then
+	:
+else
+	echo "$0: error: pigs repository directory .pig not found" >& 2
+	exit 1
+fi
+
 FORCE=false
 CACHED=false
 # I know shell-check doesn't like it but there will not be a NOT alphanumeric filename in commits
diff --git a/pigs-show b/pigs-show
--- a/pigs-show
+++ b/pigs-show
@@ -2,6 +2,13 @@
 
 REPONAME=".pig"
 
+if [ -d "$REPONAME" ]; then
+	:
+else
+	echo "$0: error: pigs repository directory .pig not found" >& 2
+	exit 1
+fi
+
 filename="$(echo "$1" | cut -d':' -f2)"
 
 if echo "$1" | grep -qE '.+:.+'; then
diff --git a/pigs-status b/pigs-status
--- a/pigs-status
+++ b/pigs-status
@@ -1,6 +1,14 @@
 #!/bin/dash
 
 REPONAME=".pig"
+
+if [ -d "$REPONAME" ]; then
+	:
+else
+	echo "$0: error: pigs repository directory .pig not found" >& 2
+	exit 1
+fi
+
 fileWrite="$REPONAME/status"
 true>"$fileWrite"
 # I know shell-check doesn't like it but there will not be a NOT alphanumeric filename in commits
