completed more tests

diff --git a/pigs-commit b/pigs-commit
--- a/pigs-commit
+++ b/pigs-commit
@@ -14,18 +14,18 @@ case $# in
 		HASA=$1
 		;;
 	*)
-		echo "./$0: error: should have arguments in style -m [commit-message]" >& 2
+		echo "./$0: error: should have arguments in style [-a] -m [commit-message]" >& 2
 		exit 1
 esac
 
 
 if [ "$CHECK" != "-m" ]; then
-	echo "./$0: error: should have arguments in style -m [commit-message] aaa" >& 2
+	echo "./$0: error: should have arguments in style [-a] -m [commit-message]" >& 2
 	exit 1
 fi
 
 if [ "$HASA" != "-a" ]; then
-	echo "./$0: error: should have arguments in style -a -m [commit-message] aaa" >& 2
+	echo "./$0: error: should have arguments in style [-a] -m [commit-message]" >& 2
 	exit 1
 else
 	if  [ "$#" -ne 2 ]; then
@@ -38,6 +38,16 @@ else
 	fi
 fi
 
+if [ ! -n "$(ls -A $REPONAME/index)" ]; then
+	echo "nothing to commit"
+	exit 1
+fi
+
+# Check if MESSAGE is assigned a value.
+if [ -z "$MESSAGE" ]; then
+    echo "./$0: error: message argument is not assigned a value" >&2
+    exit 1
+fi
 
 CURCOM=$(wc -l "$REPONAME"/log | cut -d' ' -f1)
 
